name: username_generator
description: Simple library for random and seedable username generators
version: 0.2.3
homepage: https://github.com/prikeshsavla/username_generator.dart
repository: https://github.com/prikeshsavla/username_generator.dart

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  effective_dart: ^1.0.0
